import type { Config } from "tailwindcss";
import { heroui } from "@heroui/theme";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)"],
        display: ["var(--font-display)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        "step--2": "0.75rem",
        "step--1": "0.875rem",
        "step-0": "1rem",
        "step-1": "clamp(1.125rem, 1.05rem + 0.35vw, 1.333rem)",
        "step-2": "clamp(1.3125rem, 1.15rem + 0.7vw, 1.777rem)",
        "step-3": "clamp(1.5rem, 1.25rem + 1.2vw, 2.369rem)",
        "step-4": "clamp(1.75rem, 1.3rem + 2vw, 3.157rem)",
        "step-5": "clamp(2rem, 1.3rem + 3.2vw, 4.209rem)",
        display: "clamp(2.5rem, 1.2rem + 5.6vw, 5.61rem)",
        "ui-md": "0.9375rem",
        "ui-sm": "0.875rem",
        data: "0.875rem",
        "data-sm": "0.75rem",
        sign: "0.75rem",
        key: "clamp(1.125rem, 1rem + 0.6vw, 1.5rem)",
        "flap-sm": "0.875rem",
        "flap-md": "1.125rem",
        "flap-lg": "clamp(1.25rem, 0.9rem + 1.1vw, 1.75rem)",
      },
      maxWidth: {
        container: "1360px",
        shop: "1360px",
        narrow: "1120px",
        wide: "1520px",
        read: "720px",
      },
      spacing: {
        gutter: "var(--gutter)",
      },
      colors: {
        surface: {
          DEFAULT: "var(--color-bg)",
          1: "var(--color-bg-secondary)",
          2: "var(--color-bg-tertiary)",
          warm: "var(--color-bg-warm)",
        },
        raised: "var(--color-raised)",
        deal: "var(--color-deal)",
        "on-deal": "var(--color-on-deal)",
        "logo-strip": "var(--color-logo-strip)",
        rig: "var(--color-rig)",
        floor: "var(--color-floor)",
        rule: "var(--color-rule)",
        "accent-ink": "var(--color-accent-ink)",
        "accent-edge": "var(--color-accent-edge)",
        stage: "var(--color-stage)",
        "on-stage": "var(--color-on-stage)",
        board: "var(--color-board)",
        flap: "var(--color-flap)",
        "flap-top": "var(--color-flap-top)",
        hinge: "var(--color-hinge)",
        "board-edge": "var(--color-board-edge)",
        "on-board": {
          DEFAULT: "var(--color-on-board)",
          muted: "var(--color-on-board-muted)",
          faint: "var(--color-on-board-faint)",
        },
        remark: "var(--color-remark)",
        "board-success": "var(--color-board-success)",
        "board-warning": "var(--color-board-warning)",
        "board-danger": "var(--color-board-danger)",
        "board-info": "var(--color-board-info)",
        "focus-board": "var(--color-focus-on-board)",
        link: "var(--color-link-line)",
        stop: "var(--color-stop)",
        terminus: "var(--color-terminus)",
        ink: {
          DEFAULT: "var(--color-text)",
          muted: "var(--color-text-secondary)",
          subtle: "var(--color-text-tertiary)",
        },
        brand: {
          DEFAULT: "var(--color-accent)",
          hover: "var(--color-accent-hover)",
          soft: "var(--color-accent-light)",
          2: "var(--color-accent-2)",
        },
        "on-brand": "var(--color-on-accent)",
        sale: "var(--color-accent-3)",
        line: {
          DEFAULT: "var(--color-border)",
          hover: "var(--color-border-hover)",
        },
        control: "var(--color-border-control)",
        focus: "var(--color-focus)",
        scrim: "var(--color-scrim)",
        success: { DEFAULT: "var(--color-success)", tint: "var(--color-success-tint)" },
        warning: { DEFAULT: "var(--color-warning)", tint: "var(--color-warning-tint)" },
        danger: { DEFAULT: "var(--color-danger)", tint: "var(--color-danger-tint)" },
        info: { DEFAULT: "var(--color-info)", tint: "var(--color-info-tint)" },
        "on-danger": "var(--color-on-danger)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
        accent: "var(--shadow-accent)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        overlay: "var(--shadow-overlay)",
        panel: "var(--shadow-panel)",
        flap: "var(--shadow-flap)",
      },
      borderRadius: {
        flap: "var(--radius-flap)",
        sign: "var(--radius-sign)",
        control: "var(--radius-control)",
        card: "var(--radius-card)",
        board: "var(--radius-board)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        pill: "var(--radius-pill)",
        round: "50%",
      },
      transitionTimingFunction: {
        flap: "var(--ease-flap)",
        sign: "var(--ease-sign)",
        std: "cubic-bezier(0.4, 0, 0.2, 1)",
        "in-out-strong": "cubic-bezier(0.76, 0, 0.24, 1)",
      },
      transitionDuration: {
        micro: "120ms",
        ui: "180ms",
        panel: "240ms",
        flap: "70ms",
        reveal: "560ms",
      },
      zIndex: {
        "card-item": "1",
        sticky: "40",
        dropdown: "50",
        drawer: "60",
        modal: "70",
        toast: "80",
        cookie: "90",
      },
    },
  },
  plugins: [
    heroui({
      layout: { radius: { small: "4px", medium: "6px", large: "8px" } },
      themes: {
        light: { colors: { background: "#F4F1EA", foreground: "#1B1C1D", primary: { DEFAULT: "#E2AE2F", foreground: "#1B1C1D" } } },
        dark: { colors: { background: "#121314", foreground: "#EEE9DE", primary: { DEFAULT: "#E6B84A", foreground: "#17150F" } } },
      },
    }),
  ],
};

export default config;
