import type { Config } from "tailwindcss";
import { heroui } from "@heroui/theme";

const config: Config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-sans)"],
        display: ["var(--font-display)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        "step--2": "0.75rem",
        "step--1": "0.8125rem",
        "step-0": "1rem",
        "step-1": "clamp(1.125rem, 1.08rem + 0.2vw, 1.2rem)",
        "step-2": "clamp(1.25rem, 1.15rem + 0.45vw, 1.44rem)",
        "step-3": "clamp(1.4375rem, 1.25rem + 0.85vw, 1.728rem)",
        "step-4": "clamp(1.625rem, 1.35rem + 1.35vw, 2.074rem)",
        "step-5": "clamp(1.875rem, 1.45rem + 2.05vw, 2.488rem)",
        "step-6": "clamp(2.125rem, 1.5rem + 3.05vw, 2.986rem)",
        "display-xl": "clamp(2.5rem, 0.9rem + 6.4vw, 5.5rem)",
        "ui-md": "0.9375rem",
        "ui-sm": "0.875rem",
        "ui-xs": "0.8125rem",
        data: "0.875rem",
        "data-sm": "0.75rem",
        key: "clamp(1.125rem, 1rem + 0.6vw, 1.5rem)",
      },
      maxWidth: {
        container: "1360px",
        shop: "1360px",
        narrow: "1120px",
        wide: "1560px",
        read: "720px",
      },
      spacing: {
        gutter: "var(--gutter)",
      },
      colors: {
        surface: {
          DEFAULT: "var(--color-bg)",
          1: "var(--color-bg-secondary)",
          2: "var(--color-bg-tertiary)",
          warm: "var(--color-bg-warm)",
        },
        raised: "var(--color-raised)",
        plate: "var(--color-plate)",
        "steel-hi": "var(--color-steel-hi)",
        "lamp-on": "var(--color-lamp-on)",
        "lamp-off": "var(--color-lamp-off)",
        deal: "var(--color-deal)",
        "on-deal": "var(--color-on-deal)",
        "logo-strip": "var(--color-logo-strip)",
        platform: "var(--platform)",
        type: "var(--type)",
        rig: "var(--color-rig)",
        floor: "var(--color-floor)",
        rule: "var(--color-rule)",
        "accent-ink": "var(--color-accent-ink)",
        "accent-edge": "var(--color-accent-edge)",
        stage: "var(--color-stage)",
        "on-stage": "var(--color-on-stage)",
        ink: {
          DEFAULT: "var(--color-text)",
          muted: "var(--color-text-secondary)",
          subtle: "var(--color-text-tertiary)",
        },
        brand: {
          DEFAULT: "var(--color-accent)",
          hover: "var(--color-accent-hover)",
          soft: "var(--color-accent-light)",
          2: "var(--color-accent-2)",
        },
        "on-brand": "var(--color-on-accent)",
        sale: "var(--color-accent-3)",
        line: {
          DEFAULT: "var(--color-border)",
          hover: "var(--color-border-hover)",
        },
        control: "var(--color-border-control)",
        focus: "var(--color-focus)",
        scrim: "var(--color-scrim)",
        success: { DEFAULT: "var(--color-success)", tint: "var(--color-success-tint)" },
        warning: { DEFAULT: "var(--color-warning)", tint: "var(--color-warning-tint)" },
        danger: { DEFAULT: "var(--color-danger)", tint: "var(--color-danger-tint)" },
        info: { DEFAULT: "var(--color-info)", tint: "var(--color-info-tint)" },
        "on-danger": "var(--color-on-danger)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
        accent: "var(--shadow-accent)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
        panel: "var(--shadow-panel)",
        machined: "var(--edge-machined)",
        "machined-pressed": "var(--edge-machined-pressed)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        pill: "var(--radius-pill)",
        round: "50%",
      },
      transitionTimingFunction: {
        latch: "var(--ease-latch)",
        std: "cubic-bezier(0.4, 0, 0.2, 1)",
        "in-out-strong": "cubic-bezier(0.76, 0, 0.24, 1)",
      },
      transitionDuration: {
        micro: "120ms",
        ui: "180ms",
        panel: "260ms",
        tumbler: "520ms",
        reveal: "640ms",
      },
      zIndex: {
        "box-item": "1",
        sticky: "40",
        dropdown: "50",
        drawer: "60",
        modal: "70",
        toast: "80",
        cookie: "90",
      },
      backgroundImage: {
        "steel-grain": "var(--steel-grain)",
      },
    },
  },
  plugins: [
    heroui({
      layout: { radius: { small: "0px", medium: "0px", large: "0px" } },
      themes: {
        light: { colors: { background: "#E3E7E4", foreground: "#0F1513", primary: { DEFAULT: "#0F7A50", foreground: "#FFFFFF" } } },
        dark: { colors: { background: "#0F1513", foreground: "#E4EBE7", primary: { DEFAULT: "#46D39A", foreground: "#04120B" } } },
      },
    }),
  ],
};

export default config;
